name: CI

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches:
      - main
    types:
      - ready_for_review
      - synchronize
    paths-ignore:
      - CODEOWNERS
      - README.md

  workflow_dispatch:

jobs:
  ansible:
    if: ! contains(join(github.event.issue.labels.*.name, ', '), 'no tests')
    uses: ./.github/workflows/ansible-tests.yaml

  python:
    if: ! contains(join(github.event.issue.labels.*.name, ', '), 'no tests')
    uses: ./.github/workflows/python-tests.yaml

  #docs:
  #  if: ! contains(join(github.event.issue.labels.*.name, ', '), 'no tests')
  #  uses: ./.github/workflows/doc-tests.yaml

  dummy:
    if: contains(join(github.event.issue.labels.*.name, ', '), 'no tests')
    uses: ./.github/workflows/no-tests.yaml

